[package]
name = "b"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dev-dependencies]
c = { workspace = true }
test-context = { workspace = true }